### PR TITLE
update redhat packaging

### PR DESCRIPTION
**Pull request by akva2**
add ecl3

**Approach**
Add new files to packaging definition

### CODE REVIEW

**Comment by abrautomate** [comment]
Can one of the admins verify this patch?

**Comment by jokva** [comment]
There's no need for this, does red hat packaging complain? ecl3 is not ready for packaging nor use.

**Comment by akva2** [comment]
it complains about installed but unpackaged files..

**Comment by jokva** [comment]
Hm, the default-install was done in order to make CI simpler, do you actually package HEAD?

**Comment by akva2** [comment]
yes, we have nightly builds for opm where we build ecl head.

**Comment by jokva** [comment]
My goodness.

When ecl2 is discontinued, the RH package files will be moved. I'd rather see this is a small change in the install script instead, so you can opt-out of building ecl3.

**Comment by akva2** [comment]
okay. i opened #631 which adds an option and use this to disable in packaging.

**Pull request closed without merging**
