### PR TITLE
Fix unmappable character for encoding UTF-8

### LINKED ISSUE #618: Unmappable characters for encoding UTF-8 in atomic.h
The file `lib/include/ert/util/atomic.h` contains some unmappable characters for encoding UTF-8.
I'll create a pull request to fix this.

### PR DESCRIPTION
**Pull request by matteodg**
**Issue**
Resolves #618 

**Approach**
I just replaced the offending characters with a space (as they were supposed to be)

### CODE REVIEW

**Comment by abrautomate** [comment]
Can one of the admins verify this patch?

**Comment by markusdregi** [comment]
Test this please

**Comment by jokva** [comment]
There's nothing to test, it just replaces non-breaking whitespace (at least that's what it looks like) with whitespace.

**Comment by markusdregi** [comment]
Sorry about the bluntness @matteodg (and @jokva). The statement above was just to get the tests on Jenkins to run...

@matteodg Did you try removing the entire file as suggested by @joakim-hove?

**Comment by matteodg** [comment]
> Sorry about the bluntness @matteodg (and @jokva). The statement above was just to get the tests on Jenkins to run...
No problem.

> @matteodg Did you try removing the entire file as suggested by @joakim-hove?
Actually I did not yet: I can do it later today.

**Comment by matteodg** [comment]
Just tested removing that file and I can compile under Windows x86_64 using MSYS2.

**Comment by markusdregi** [comment]
@matteodg That sounds great! Then I would suggest just removing the entire file :+1:

Will you update this PR?

**Comment by markusdregi** [comment]
Jenkins, test this please

**Pull request merged**
