### PR TITLE
Avoid installing with .c.x suffix, only .x

### LINKED ISSUE #684: Installation suffixes for binary files
Due to a change in 2018, some of the applications, like "ecl_unpack" now installs as `ecl_unpack.c.x` instead of `ecl_unpack.x`.

Other applications, like `summary.x` is still `summary.x` as before. Perhaps the `.c.x` was not intentional.

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves #684 

**Intention**

Change the file suffix for the binary targets 
`ecl_pack,  ecl_unpack,  kw_extract, grid_info, grid_dump, grid_dump_ascii, select_test, load_test`
from `*.c.x` or `*.cpp.x` to only `*.x`

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by pgdr** [comment]
Can you split your patch into two commits and state in the PR description what your intention is?

It's not clear from the issue that you link to what is the intended consequence of this patch.

**Comment by berland** [comment]
I fail to see how to split the commit into two (meaningful) commits (?).

Added text to PR describing the intention.

**Comment by markusdregi** [comment]
I've tested the installation procedure on my machine and it seems to work here also. Waiting for further updates from @pgdr

**Pull request merged**
